package com.pichincha.cuentas.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Getter;
import lombok.Setter;

@Getter @Setter
@DynamoDBTable(tableName = "cuenta")
public class Account {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName ="numeroCuenta")
    private String numeroCuenta;

    @DynamoDBAttribute(attributeName ="tipoCuenta")
    private String tipoCuenta;


    @DynamoDBAttribute(attributeName ="estado")
    private String estado;

    @DynamoDBAttribute(attributeName ="idCliente")
    private String idCliente;

    @DynamoDBAttribute(attributeName ="total")
    private double total;

}
