package com.pichincha.cuentas.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDate;

@DynamoDBTable(tableName = "transacion")
@Getter @Setter
public class Transaction {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private int id;

    @DynamoDBAttribute(attributeName ="numeroCuenta")
    private String numeroCuenta;

    @DynamoDBAttribute(attributeName ="tipoTransacion")
    private String tipoTransacion;


    @DynamoDBAttribute(attributeName ="valor")
    private double valor;

    @DynamoDBAttribute(attributeName ="fecha")
    private LocalDate fecha;
    @DynamoDBAttribute(attributeName ="idCliente")
    private String idCliente;
}
